import { Cart } from "@/features/cart/Cart";
import { Header } from "@/features/dashboard/Header";
import { Hero } from "@/features/dashboard/Hero";
import { ProductList } from "@/features/products/ProductList";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>[Nome Loja]</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <ProductList />
      <Cart />
    </>
  );
};

export default Home;
