import { Header } from "@/features/dashboard/Header";
import { Hero } from "@/features/dashboard/Hero";
import { ProductList } from "@/features/products/ProductList";
import { apiSSG } from "@/utils/trpc-ssr";
import { GetStaticProps, GetStaticPropsContext, type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="bg-zinc-900">
      <Head>
        <title>[Nome Loja]</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <ProductList />
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (
  context: GetStaticPropsContext
) => {
  await apiSSG.products.getAll.prefetch();

  return {
    props: {
      trpcState: apiSSG.dehydrate(),
    },
  };
};
